### ISSUE TITLE
Creating Delete Route 

### ISSUE THREAD

**Issue by FatimmmaaaaK** [The-Bit-Busters/inventory-app#10]
User Stories: As a user id like to have the ability to delete an item from my database. 
Implementation Details: Make a new route requiring the specific items id so that it can find the item we want to delete, and then delete that item from the database. Then we can await, findAll to return all items remaining in database.

**Comment by nathancai97** [comment]
Completed! 
https://github.com/The-Bit-Busters/inventory-app/pull/12
